# Generated by Django 4.2.6 on 2023-12-01 17:39

import books.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.category')),
            ],
            options={
                'db_table': 'subcategories',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='Отсутствует описание')),
                ('image', models.ImageField(default='error_404/Error404img.png', upload_to='books/')),
                ('e_book', models.FileField(upload_to='e_books_files')),
                ('inventory_number', models.CharField(max_length=150)),
                ('language', models.CharField(choices=[('Кыргызский', 'Кыргызский'), ('Русский', 'Русский'), ('Английский', 'Английский'), ('Немецкий', 'Немецкий')], max_length=150)),
                ('edition_year', models.CharField(max_length=4)),
                ('purchase_price', models.CharField(max_length=10, validators=[books.models.validate_price])),
                ('purchase_time', models.DateField()),
                ('quantity', models.IntegerField()),
                ('isPossibleToOrder', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0)),
                ('orders', models.IntegerField(default=0)),
                ('reviews', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.subcategory')),
            ],
            options={
                'db_table': 'books',
                'ordering': ['reviews'],
            },
        ),
    ]
