# Generated by Django 4.2.6 on 2023-10-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='media/error_404/Error404img.png', upload_to='media/books/'),
        ),
    ]
