# Generated by Django 4.2.6 on 2023-10-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='media/not_found_404_image/Error404img.png', upload_to='media/books/'),
        ),
    ]
