# Generated by Django 4.2.6 on 2023-10-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_reviews_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='../media/error_404/Error404img.png', upload_to='../media/books/'),
        ),
    ]
