# Generated by Django 4.2.6 on 2023-10-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['reviews']},
        ),
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
    ]
