# Generated by Django 4.2.6 on 2023-10-23 14:26

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_book_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(
                default="media/error_404/Error404img.png",
                upload_to=books.models.upload_to,
            ),
        ),
    ]
