# Generated by Django 4.2.6 on 2023-10-23 14:32

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_book_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(
                default="/home/orenvadi/INAI_library/mediaerror_404/Error404img.png",
                upload_to=books.models.upload_to,
            ),
        ),
    ]
