# Generated by Django 4.2.6 on 2023-10-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='D:\\INAI_library\\media\\error_404', upload_to='D:\\INAI_library\\media\\books'),
        ),
    ]
