# Generated by Django 4.2.7 on 2023-11-08 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='error_404/Error404img.png', upload_to='books/'),
        ),
    ]
