# Generated by Django 4.2.6 on 2023-11-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='home/orenvady/Repos/python/INAI_librarymediaerror_404/', upload_to='home/orenvady/Repos/python/INAI_librarymediabooks/'),
        ),
    ]
