# Generated by Django 4.2.6 on 2023-10-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterModelTable(
            name='message',
            table='messages',
        ),
    ]
