# Generated by Django 4.2.7 on 2023-11-24 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_messages', '0002_alter_message_options_alter_message_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author',
        ),
    ]
