# Generated by Django 4.2.6 on 2023-10-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_book_review_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='books',
            new_name='book',
        ),
    ]
