# Generated by Django 4.2.6 on 2023-10-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_books_review_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterModelTable(
            name='review',
            table='reviews',
        ),
    ]
