# Generated by Django 4.2.7 on 2023-11-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_due_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ожидает проверки', 'Ожидает проверки'), ('В обработке', 'В обработке'), ('Выполнен', 'Выполнен'), ('Ошибка', 'Ошибка')], default='Ожидает проверки', max_length=50),
        ),
    ]
